# Generated by Django 3.0.3 on 2020-03-03 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Accessory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'accessory_tab',
            },
        ),
        migrations.CreateModel(
            name='Biker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=50)),
                ('user_name', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=15, unique=True)),
                ('email', models.CharField(max_length=100, unique=True)),
                ('hashed_password', models.CharField(default='', max_length=255)),
                ('password_salt', models.CharField(default='', max_length=128)),
                ('is_active', models.BooleanField(default=1)),
                ('main_address_id', models.IntegerField(default=-1, null=True)),
                ('date_of_birth', models.DateField(null=True)),
                ('gender', models.SmallIntegerField(default=0)),
                ('job', models.CharField(default='', max_length=50)),
                ('facebook', models.CharField(default='', max_length=100)),
                ('like_number', models.IntegerField(default=0)),
                ('updated_time', models.DateTimeField(auto_now_add=True)),
                ('created_time', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'db_table': 'biker_tab',
            },
        ),
        migrations.CreateModel(
            name='BikerAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(default='', max_length=255)),
                ('contact_name', models.CharField(default='', max_length=255)),
                ('contact_phone', models.CharField(default='', max_length=15)),
                ('biker_id', models.BigIntegerField(db_index=True)),
                ('district_id', models.BigIntegerField()),
                ('province_id', models.BigIntegerField()),
                ('ward_id', models.BigIntegerField()),
                ('longitude', models.DecimalField(decimal_places=6, default=0, max_digits=20)),
                ('latitude', models.DecimalField(decimal_places=6, default=0, max_digits=20)),
                ('type', models.SmallIntegerField(default=0)),
                ('deleted', models.SmallIntegerField(default=0)),
                ('updated_time', models.DateTimeField(auto_now_add=True)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'biker_address_tab',
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_parent_id', models.IntegerField(default=-1)),
                ('biker_id', models.IntegerField(default=-1)),
                ('post_id', models.IntegerField(default=-1)),
                ('accessory_id', models.IntegerField(default=-1)),
                ('content', models.TextField(default='')),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('updated_time', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'comment_tab',
            },
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_id', models.IntegerField(default=-1)),
                ('post_id', models.IntegerField(default=-1)),
                ('biker_id', models.IntegerField(default=-1)),
                ('accessory_id', models.IntegerField(default=-1)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('updated_time', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'like_tab',
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('biker_id', models.IntegerField(default=-1)),
                ('like_number', models.IntegerField(default=0)),
                ('share_number', models.IntegerField(default=0)),
                ('view_number', models.IntegerField(default=0)),
                ('title', models.CharField(default='', max_length=255)),
                ('description', models.TextField(default='', null=True)),
                ('is_active', models.SmallIntegerField(default=1)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('updated_time', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'post_tab',
            },
        ),
        migrations.CreateModel(
            name='PostImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_id', models.IntegerField(default=-1)),
                ('url', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'post_image_tab',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(default=-1)),
                ('name', models.CharField(default='', max_length=100)),
                ('description', models.TextField(default='', null=True)),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=20)),
                ('sale_status', models.SmallIntegerField(default=0)),
                ('is_active', models.SmallIntegerField(default=0)),
                ('accessory_id', models.SmallIntegerField()),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('updated_time', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'product_tab',
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.IntegerField(default=-1)),
                ('url', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'product_image_tab',
            },
        ),
        migrations.CreateModel(
            name='Province',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'province_tab',
            },
        ),
    ]
