# Generated by Django 2.0.5 on 2019-12-14 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('racing', '0002_auto_20191214_1316'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='status',
            field=models.SmallIntegerField(default=1),
        ),
    ]
