# Generated by Django 2.0.5 on 2019-12-14 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('racing', '0003_post_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='accessory',
            old_name='status',
            new_name='is_active',
        ),
        migrations.RenameField(
            model_name='biker',
            old_name='hash_password',
            new_name='hashed_password',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='status',
            new_name='is_active',
        ),
        migrations.AlterField(
            model_name='biker',
            name='password_salt',
            field=models.CharField(default='', max_length=128),
        ),
    ]
