# Generated by Django 2.0.5 on 2019-12-14 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('racing', '0004_auto_20191214_1536'),
    ]

    operations = [
        migrations.AlterField(
            model_name='biker',
            name='main_address_id',
            field=models.IntegerField(default=-1, null=True),
        ),
    ]
