# Generated by Django 3.0.3 on 2020-02-12 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('racing', '0005_auto_20191214_1542'),
    ]

    operations = [
        migrations.CreateModel(
            name='Token',
            fields=[
                ('token', models.CharField(default='', max_length=32, primary_key=True, serialize=False)),
                ('biker_id', models.IntegerField()),
                ('expiry_time', models.DateTimeField()),
                ('app_type', models.SmallIntegerField(default=1)),
            ],
            options={
                'db_table': 'token_tab',
            },
        ),
        migrations.AlterField(
            model_name='biker',
            name='email',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
