# Generated by Django 3.0.3 on 2020-02-12 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('racing', '0006_auto_20200212_1552'),
    ]

    operations = [
        migrations.AlterField(
            model_name='token',
            name='token',
            field=models.TextField(default='', max_length=500, primary_key=True, serialize=False),
        ),
    ]
