# Generated by Django 3.0.3 on 2020-02-12 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('racing', '0007_auto_20200212_1619'),
    ]

    operations = [
        migrations.AlterField(
            model_name='token',
            name='token',
            field=models.TextField(default='', primary_key=True, serialize=False),
        ),
    ]
