# Generated by Django 3.0.3 on 2020-02-12 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('racing', '0008_auto_20200212_1620'),
    ]

    operations = [
        migrations.AlterField(
            model_name='token',
            name='token',
            field=models.CharField(default='', max_length=255, primary_key=True, serialize=False),
        ),
    ]
