# Generated by Django 3.0.3 on 2020-02-13 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('racing', '0009_auto_20200212_1621'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Token',
        ),
    ]
