version: '3'

services:
  db:
    image: mysql:5.7
    ports:
      - '8080:8080'
    environment:
       MYSQL_DATABASE: 'vietnam_racing'
       MYSQL_USER: 'root'
       MYSQL_PASSWORD: 'root'
       MYSQL_ROOT_PASSWORD: 'root'
  web:
    build: .
    command: python manage.py runserver localhost:8000
    volumes:
      - .:/vietnamracing
    ports:
      - "8000:8000"
    depends_on:
      - db